#config file example, please don't use quotes
###########################
#
#bazarr_url: the full URL of your bazarr instance (e.g., https://bazarr.example.com or http://192.168.1.100:6767)
bazarr_url: <bazarr_url>
#
#bazarr_token: you can get this from bazarr setting>general . no quotes needed.
bazarr_token: <Bazarr_api_token>
